services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: postgres
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./db/create_user.sh:/docker-entrypoint-initdb.d/1_create_user.sh
      - ./db/init.sql:/docker-entrypoint-initdb.d/2_create_db.sql
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_passwd
      POSTGRES_DB: docker
    secrets:
      - db_passwd
      - db_passwd_back
      - db_user
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $(cat /run/secrets/db_user) -d docker"]
      interval: 5s
      timeout: 5s
      retries: 5
  backend:
    build: ./backend
    depends_on: 
      postgres:
        condition: service_healthy
    ports:
      - 5000:5000
    volumes:
      - ./uploads:/uploads
    develop:
      watch:
        - action: sync
          path: backend
          target: /code
    secrets:
      - db_passwd_back

secrets:
  db_passwd_back:
    file: ./db/pwd_back.txt
  db_passwd:
    file: ./db/pwd.txt
  db_user:
    file: ./db/user.txt
