services:
  postgres:
    build: 
      context: ./db
      secrets:
        - db_passwd
        - db_passwd_back
        - db_user
    container_name: postgres
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    # or set shared memory limit when deploy via swarm stack
    #volumes:
    #  - type: tmpfs
    #    target: /dev/shm
    #    tmpfs:
    #      size: 134217728 # 128*2^20 bytes = 128Mb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER_FILE: /run/secrets/db_user
      POSTGRES_PASSWORD_FILE: /run/secrets/db_passwd
      POSTGRES_DB: docker
    secrets:
      - db_passwd
      - db_passwd_back
      - db_user
  backend:
    build: ./backend
    depends_on: 
      - postgres
    ports:
      - 5000:5000
    develop:
      watch:
        - action: sync
          path: backend
          target: /code
    secrets:
      - db_passwd_back

secrets:
  db_passwd_back:
    file: ./db/pwd_back.txt
  db_passwd:
    file: ./db/pwd.txt
  db_user:
    file: ./db/user.txt
